---
title: "DMML_test"
author: " "
date: "`r Sys.Date()`"
output: html_document
---

```{r}
library(tidyverse)
library(dplyr)
library(ggplot2)
library(data.table)
```


```{r}
merged_df <- fread("merged_df.csv")
merged_df$survival_time = as.numeric(difftime(merged_df$deathtime, merged_df$admittime, units = "day"))
```


```{r}
sum(is.na(merged_df$outcome))
```

```{r}
# Histograms for continuous variables
continuous_vars <- c('heart rate', 'Systolic blood pressure', 'Diastolic blood pressure', 'Respiratory rate', 'temperature', 'SP O2')

merged_df %>%
  select(all_of(continuous_vars)) %>%
  gather(key = "variable", value = "value") %>%
  ggplot(aes(x = value)) +
  geom_histogram(bins = 15, fill = "orange", color = "black") +
  facet_wrap(~variable, scales = "free") +
  theme_minimal() +
  labs(title = "Distribution of Continuous Variables", x = "Value", y = "Frequency")

```



#t test  


```{r}
cont <- c("age", "BMI", "heart rate", "Systolic blood pressure", "Diastolic blood pressure", "Respiratory rate", "temperature", "SP O2", "Urine output", "hematocrit", "RBC", "MCH", "MCHC", "MCV", "RDW", "Leucocyte", "Platelets", "Neutrophils", "Basophils", "Lymphocyte", "PT", "INR", "NT proBNP", "Creatine kinase", "Creatinine", "Urea nitrogen", "glucose", "Blood potassium", "Blood sodium", "Blood calcium", "Chloride", "Anion gap", "Magnesium ion", "PH", "Bicarbonate", "Lactic acid", "PCO2")

for (var in cont) {
  t_test <- t.test(merged_df[[var]] ~ merged_df$outcome, data = merged_df)
  print(paste("T-test for", var))
  print(t_test)
}
```



# chi-square test 

```{r}
cat <- c("gendera", "hypertensive", "atrialfibrillation", "CHD with no MI", "diabetes", "deficiencyanemias", "depression", "Hyperlipemia", "Renal failure", "COPD")

for (var in cat) {
  chi_sq <- chisq.test(table(merged_df[[var]], merged_df$outcome))
  print(paste("Chi-square test for", var))
  print(chi_sq)
}
```




# some new columns
```{r}
#Total of each patients' comorbidity score - comorb_score
merged_df$comorb_score = merged_df$gendera + merged_df$hypertensive + merged_df$atrialfibrillation + merged_df$`CHD with no MI` + merged_df$diabetes + merged_df$deficiencyanemias + merged_df$depression + merged_df$Hyperlipemia + merged_df$`Renal failure` + merged_df$COPD

#Length of stay for survivors - LOS
merged_df$LOS = as.numeric(difftime(merged_df$dischtime, merged_df$admittime, units = "days")) * !merged_df$outcome
merged_df$LOS = ifelse(!merged_df$outcome, as.numeric(difftime(merged_df$dischtime, merged_df$admittime, units = "days")), NA)

#total length of stay for those who both survived (discharged) and died - tLOS
merged_df$tLOS <- ifelse(is.na(merged_df$LOS), merged_df$survival_time, merged_df$LOS)

```



```{r}
full_model <- glm(outcome ~ gendera + hypertensive + atrialfibrillation + `CHD with no MI` + 
            diabetes + deficiencyanemias + depression + Hyperlipemia + `Renal failure` + 
            COPD + age + `heart rate` + BMI + `Systolic blood pressure` + 
            `Diastolic blood pressure` + `Respiratory rate` + temperature + 
            `SP O2` + `Urine output` + hematocrit + RBC + MCH + MCHC + MCV + 
            RDW + Leucocyte + Platelets + Neutrophils + Basophils + Lymphocyte + 
            PT + INR + `NT-proBNP` + `Creatine kinase` + Creatinine + `Urea nitrogen` + 
            glucose + `Blood potassium` + `Blood sodium` + `Blood calcium` + Chloride + 
            `Anion gap` + `Magnesium ion` + PH + Bicarbonate + `Lactic acid` + PCO2, 
            data = merged_df, family = "binomial")
summary(full_model)
```


```{r}
current_aic <- AIC(full_model)
while (TRUE) {
    current_aic <- AIC(full_model)
    reduced_model <- step(full_model, direction = "backward")
    reduced_aic <- AIC(reduced_model)
    if (reduced_aic > current_aic) break
    full_model <- reduced_model
}
summary(full_model)
```





