---
title: "missing_data_hf"
author: "Peter"
date: "`r Sys.Date()`"
output: html_document
---

```{r}

library(data.table)

# Assuming your dataset is a data.table called merged_df
merged_dt <- as.data.table(merged_df)  # Convert to data.table if it's not already

# Specify the columns to exclude from the NA check
exclude_columns <- c("survival_time", "deathtime", "LOS")

# Create a logical vector indicating which columns to include in the NA check
include_columns <- setdiff(names(merged_dt), exclude_columns)

# Subset the data.table to include only rows without NAs in the specified columns
merged_dt_clean <- merged_dt[complete.cases(merged_dt[, ..include_columns])]

# Convert back to data.frame if needed
merged_df_clean <- as.data.frame(merged_dt_clean)

```



```{r}
get_wd()

library(data.table)

# Read the dataset from the specified location
file_path <- "multiple_imputation_NEW.csv"
mult_impute_df <- fread(file_path)

# Display the first few rows of the dataset to verify
head(mult_impute_df)


```


```{r}
mult_impute_df %>%
  summarize(PCO2old = mean(PCO2, na.rm = TRUE))


```


